version: '3.6'

services:
  spark-master:
    image: bitnami/spark:latest
    environment:
      - SPARK_MODE=master
      - SPARK_LOCAL_IP=spark-master
    ports:
      - '9093:8080'
      - '4040:4040'
      - '7077:7077'
    volumes:
      - ./apps:/apps
      - ./data:/data

  spark-worker-1:
    image: bitnami/spark:latest
    ports:
      - "9091:8081"
      - "7002:7000"
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_EXECUTOR_MEMORY=1G
      - SPARK_WORKER_CORES=1
    depends_on:
      - spark-master
    volumes:
      - ./apps:/apps
      - ./data:/data

  spark-worker-2:
    image: bitnami/spark:latest
    ports:
      - "9094:8081"
      - "7001:7000"
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_EXECUTOR_MEMORY=1G
      - SPARK_WORKER_CORES=1
    depends_on:
      - spark-master
    volumes:
      - ./apps:/apps
      - ./data:/data
